/// Fixed 8-byte header pre-prepended to every TDS packet.
///
/// ## Implementing
///
/// Implementors are generated by the [`tds_packet_header!`] macro.
/// It sets `type = $ty` as the default and derives `from_bytes`/`as_bytes`
/// and `core::fmt::Display`.
///
/// ## Example
/// ```rust,ignore
/// tds_packet_header!("Example")
/// ```
pub trait TDSPacketHeader: Sized {
    /// Returns the type byte. For client messages this is a [`ClientMessageType`](crate::tds::types::prelude::ClientMessageType) variant.
    /// All server responses use [`SERVER_PACKET_TYPE`](crate::tds::types::prelude::SERVER_PACKET_TYPE) (0x04).
    fn ty(&self) -> u8;
    /// Returns the status byte.
    ///
    /// See: [`MessageStateStatus`](crate::tds::types::prelude::MessageStateStatus)
    fn status(&self) -> u8;
    /// Returns size of the TDS stream body in bytes.
    fn length(&self) -> u16;
    /// Returns the server process ID (SPID) of the connection.
    fn spid(&self) -> u16;
    /// Returns the packet sequence number, wrapping at 255.
    fn packet_id(&self) -> u8;
    /// Returns the window size. Reserved; always set to 0x00.
    fn window(&self) -> u8 {
        0x00
    }
    // Size of the TDS header in bytes.
    const LENGTH: usize = 8;
    // Returns the TDPackerHeader as an 8-byte array.
    fn as_bytes(&self) -> [u8; 8] {
        [
            self.ty(),
            self.status(),
            (self.length() >> 8) as u8,
            (self.length() & 0xff) as u8,
            (self.spid() >> 8) as u8,
            (self.spid() & 0xff) as u8,
            self.packet_id(),
            self.window(),
        ]
    }
    /// Deserialises a header from its 8-byte wire representation.
    fn from_bytes(buf: &[u8; 8]) -> Self;
}

/// Generates a [`TDSPacketHeader`] implementation for a named header struct.
///
/// Expands to a stuct with fields and associated accessors:
/// - `ty`
/// - `status`
/// - `length`
/// - `spid`
/// - `packet_id`
/// - `window`
///
/// It also provides impls for [`TDSPacketHeader`], `Default` and `Display`.
///
/// ## Arguments
///
/// - `$ident` - The name of the struct to be generated. e.g. `PreLoginHeader`.
/// - `$ty` - the [`ClientMessageType`](crate::tds::types::prelude::ClientMessageType) variant as u8.
#[doc(hidden)]
#[macro_export]
macro_rules! tds_packet_header {
    ($ident:ident, $ty:expr) => {

        #[derive(Debug, Clone, Copy, Builder)]
        #[builder(no_std, setter(strip_option), default)]
        pub struct $ident {
            pub(crate) ty: u8,
            pub(crate) status: u8,
            pub(crate) length: u16,
            pub(crate) spid: u16,
            pub(crate) packet_id: u8,
            pub(crate) window: u8,
        }

        #[rustfmt::skip]
        impl TDSPacketHeader for $ident {
            fn ty(&self) -> u8 { self.ty }
            fn status(&self) -> u8 { self.status }
            fn length(&self) -> u16 { self.length }
            fn spid(&self) -> u16 { self.spid }
            fn packet_id(&self) -> u8 { self.packet_id }
            fn from_bytes(buf: &[u8; 8]) -> Self {
                Self {
                    ty: buf[0],
                    status: buf[1],
                    length: u16::from_be_bytes([buf[2], buf[3]]),
                    spid: u16::from_be_bytes([buf[4], buf[5]]),
                    packet_id: buf[6],
                    window: buf[7],
                }
            }
        }
        impl Default for $ident {
            fn default() -> Self {
                Self {
                    ty: $ty as u8,
                    status: MessageStateStatus::EndOfMessage as u8,
                    length: 0x08,
                    spid: 0x00,
                    packet_id: 0x00,
                    window: 0x00,
                }
            }
        }

        impl core::fmt::Display for $ident {
            fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
                write!(f, "HEADER \ntype:\t\t{}\nstatus:\t\t{}\nlength:\t\t{}\nspid\t\t{}\npacket_id\t{}\nwindow\t\t{}",
                    ClientMessageType::try_from(self.ty as u8).map_err(|_| core::fmt::Error)?,
                    MessageStateStatus::try_from(self.status as u8).map_err(|_| core::fmt::Error)?,
                    self.length,
                    self.spid,
                    self.packet_id,
                    self.window)
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use crate::tds::types::prelude::ClientMessageType;
    use crate::tds::types::prelude::PreLoginHeader;
    use crate::tds::types::prelude::TDSPacketHeader;

    #[test]
    fn test_from_bytes() {
        let bytes = [
            ClientMessageType::PreLogin as u8,
            0x01,
            0x00,
            0x2f,
            0x00,
            0x00,
            0x01,
            0x00,
        ];
        let header = PreLoginHeader::from_bytes(&bytes);

        assert_eq!(header.status, 0x01);
        assert_eq!(header.length, 0x2f);
        assert_eq!(header.spid, 0x00);
        assert_eq!(header.packet_id, 0x01);
        assert_eq!(header.window, 0x00);
    }
}
